[2024-10-21T06:05:25.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-21T06:05:25.890+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_table manual__2024-10-21T06:04:54.973773+00:00 [queued]>
[2024-10-21T06:05:25.935+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_table manual__2024-10-21T06:04:54.973773+00:00 [queued]>
[2024-10-21T06:05:25.938+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-21T06:05:26.017+0000] {taskinstance.py:2888} INFO - Executing <Task(PinotTableSubmitOperator): submit_table> on 2024-10-21 06:04:54.973773+00:00
[2024-10-21T06:05:26.044+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=244) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-21T06:05:26.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_table', 'manual__2024-10-21T06:04:54.973773+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpqx8kt7e6']
[2024-10-21T06:05:26.048+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2024-10-21T06:05:26.051+0000] {standard_task_runner.py:105} INFO - Job 175: Subtask submit_table
[2024-10-21T06:05:26.402+0000] {task_command.py:467} INFO - Running <TaskInstance: table_dag.submit_table manual__2024-10-21T06:04:54.973773+00:00 [running]> on host b5fa23871e33
[2024-10-21T06:05:26.799+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saisunny' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T06:04:54.973773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T06:04:54.973773+00:00'
[2024-10-21T06:05:26.803+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-21T06:05:26.805+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-21T06:05:26.807+0000] {logging_mixin.py:190} INFO - Current task name:submit_table state:running start_date:2024-10-21 06:05:25.892945+00:00
[2024-10-21T06:05:26.809+0000] {logging_mixin.py:190} INFO - Dag name:table_dag and current dag run status:running
[2024-10-21T06:05:26.811+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-21T06:05:26.863+0000] {pinot_table_operator.py:38} ERROR - An Error Occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9230a1c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-10-21T06:05:26.889+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-21T06:05:26.891+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_table, run_id=manual__2024-10-21T06:04:54.973773+00:00, execution_date=20241021T060454, start_date=20241021T060525, end_date=20241021T060526
[2024-10-21T06:05:26.918+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-21T06:05:26.923+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-21T06:05:26.925+0000] {logging_mixin.py:190} INFO - Dag name:table_dag queued_at:2024-10-21 06:04:54.995390+00:00
[2024-10-21T06:05:26.927+0000] {logging_mixin.py:190} INFO - Task hostname:b5fa23871e33 operator:PinotTableSubmitOperator
[2024-10-21T06:05:26.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-21T06:05:27.044+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-21T06:05:27.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
