[2024-10-20T23:06:57.539+0000] {processor.py:186} INFO - Started process (PID=1372) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:06:57.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:06:57.547+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:06:57.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:06:57.664+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:06:57.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:06:57.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:06:57.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.292 seconds
[2024-10-20T23:07:15.171+0000] {processor.py:186} INFO - Started process (PID=1412) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:15.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:07:15.180+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:15.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:15.254+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:15.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 29
    submit_schema = 
                    ^
SyntaxError: invalid syntax
[2024-10-20T23:07:15.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:15.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.226 seconds
[2024-10-20T23:07:29.182+0000] {processor.py:186} INFO - Started process (PID=1441) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:29.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:07:29.187+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:29.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:29.248+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:29.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:07:29.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:29.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.114 seconds
[2024-10-20T23:07:45.413+0000] {processor.py:186} INFO - Started process (PID=1479) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:45.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:07:45.417+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:45.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:45.461+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:07:45.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:07:45.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:07:45.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.084 seconds
[2024-10-20T23:08:15.906+0000] {processor.py:186} INFO - Started process (PID=1546) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:15.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:08:15.909+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:15.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:15.929+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:15.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:08:15.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:15.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.062 seconds
[2024-10-20T23:08:35.934+0000] {processor.py:186} INFO - Started process (PID=1597) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:35.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:08:35.936+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:35.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:35.970+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:35.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:08:35.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:36.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.077 seconds
[2024-10-20T23:08:59.275+0000] {processor.py:186} INFO - Started process (PID=1636) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:59.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:08:59.281+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:59.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:59.367+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:08:59.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:08:59.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:08:59.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.195 seconds
[2024-10-20T23:09:29.585+0000] {processor.py:186} INFO - Started process (PID=1703) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:09:29.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:09:29.590+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:09:29.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:09:29.644+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:09:29.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:09:29.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:09:29.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.098 seconds
[2024-10-20T23:10:00.406+0000] {processor.py:186} INFO - Started process (PID=1770) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:00.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:10:00.411+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:00.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:00.449+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:00.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:10:00.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:00.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.078 seconds
[2024-10-20T23:10:02.438+0000] {processor.py:186} INFO - Started process (PID=1776) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:02.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:10:02.440+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:02.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:02.464+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:02.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:10:02.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:02.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.055 seconds
[2024-10-20T23:10:13.752+0000] {processor.py:186} INFO - Started process (PID=1810) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:13.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:10:13.760+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:13.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:13.837+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:13.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:10:13.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:13.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.153 seconds
[2024-10-20T23:10:44.024+0000] {processor.py:186} INFO - Started process (PID=1878) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:44.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:10:44.028+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:44.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:44.083+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:10:44.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:10:44.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:10:44.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.103 seconds
[2024-10-20T23:11:14.356+0000] {processor.py:186} INFO - Started process (PID=1945) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:14.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:11:14.358+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:11:14.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:14.379+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:11:14.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 18, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:11:14.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:14.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.066 seconds
[2024-10-20T23:11:41.318+0000] {processor.py:186} INFO - Started process (PID=2007) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:41.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:11:41.320+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:11:41.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:41.344+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:11:41.342+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8
    from 
         ^
SyntaxError: invalid syntax
[2024-10-20T23:11:41.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:11:41.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.061 seconds
[2024-10-20T23:12:11.482+0000] {processor.py:186} INFO - Started process (PID=2071) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:11.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:12:11.485+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:12:11.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:11.512+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:12:11.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8
    from 
         ^
SyntaxError: invalid syntax
[2024-10-20T23:12:11.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:11.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.092 seconds
[2024-10-20T23:12:32.446+0000] {processor.py:186} INFO - Started process (PID=2108) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:32.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:12:32.451+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:12:32.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:32.542+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:12:32.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
ImportError: cannot import name 'PinotSchemaSubmitOperator' from 'pinot_schema_operator' (/opt/airflow/plugins/pinot_schema_operator.py)
[2024-10-20T23:12:32.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:12:32.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.133 seconds
[2024-10-20T23:13:03.091+0000] {processor.py:186} INFO - Started process (PID=2175) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:03.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:13:03.109+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:13:03.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:03.180+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:13:03.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
ImportError: cannot import name 'PinotSchemaSubmitOperator' from 'pinot_schema_operator' (/opt/airflow/plugins/pinot_schema_operator.py)
[2024-10-20T23:13:03.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:03.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.142 seconds
[2024-10-20T23:13:33.424+0000] {processor.py:186} INFO - Started process (PID=2242) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:33.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:13:33.427+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:13:33.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:33.456+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:13:33.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
ImportError: cannot import name 'PinotSchemaSubmitOperator' from 'pinot_schema_operator' (/opt/airflow/plugins/pinot_schema_operator.py)
[2024-10-20T23:13:33.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:13:33.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.062 seconds
[2024-10-20T23:14:03.724+0000] {processor.py:186} INFO - Started process (PID=2309) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:03.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:14:03.728+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:14:03.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:03.778+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:14:03.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 5
    @apply_defaults
                   ^
IndentationError: unexpected unindent
[2024-10-20T23:14:03.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:03.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.098 seconds
[2024-10-20T23:14:34.355+0000] {processor.py:186} INFO - Started process (PID=2376) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:34.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:14:34.358+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:14:34.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:34.412+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:14:34.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 5
    @apply_defaults
                   ^
IndentationError: unexpected unindent
[2024-10-20T23:14:34.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:14:34.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.088 seconds
[2024-10-20T23:15:04.746+0000] {processor.py:186} INFO - Started process (PID=2443) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:04.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:15:04.749+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:15:04.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:04.824+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:15:04.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 5
    @apply_defaults
                   ^
IndentationError: unexpected unindent
[2024-10-20T23:15:04.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:04.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.108 seconds
[2024-10-20T23:15:35.382+0000] {processor.py:186} INFO - Started process (PID=2510) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:35.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:15:35.385+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:15:35.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:35.422+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:15:35.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 5
    @apply_defaults
                   ^
IndentationError: unexpected unindent
[2024-10-20T23:15:35.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:15:35.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.069 seconds
[2024-10-20T23:16:06.192+0000] {processor.py:186} INFO - Started process (PID=2577) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:06.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:16:06.197+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:16:06.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:06.249+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:16:06.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 5
    @apply_defaults
                   ^
IndentationError: unexpected unindent
[2024-10-20T23:16:06.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:06.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.088 seconds
[2024-10-20T23:16:36.682+0000] {processor.py:186} INFO - Started process (PID=2644) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:36.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:16:36.687+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:16:36.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:36.738+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:16:36.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 8
    def __int__(self), folder_path, pin:
                     ^
SyntaxError: expected ':'
[2024-10-20T23:16:36.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:16:36.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.098 seconds
[2024-10-20T23:17:07.255+0000] {processor.py:186} INFO - Started process (PID=2711) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:07.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:17:07.258+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:17:07.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:07.302+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:17:07.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:17:07.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:07.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.082 seconds
[2024-10-20T23:17:37.587+0000] {processor.py:186} INFO - Started process (PID=2778) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:37.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:17:37.590+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:17:37.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:37.638+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:17:37.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:17:37.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:17:37.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.081 seconds
[2024-10-20T23:18:08.045+0000] {processor.py:186} INFO - Started process (PID=2845) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:08.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:18:08.049+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:18:08.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:08.088+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:18:08.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 13
    def execute
               ^
SyntaxError: expected '('
[2024-10-20T23:18:08.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:08.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.074 seconds
[2024-10-20T23:18:38.409+0000] {processor.py:186} INFO - Started process (PID=2912) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:38.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:18:38.414+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:18:38.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:38.487+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:18:38.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 18
    
    ^
IndentationError: expected an indented block after 'try' statement on line 17
[2024-10-20T23:18:38.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:18:38.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.134 seconds
[2024-10-20T23:19:08.777+0000] {processor.py:186} INFO - Started process (PID=2979) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:08.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:19:08.782+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:19:08.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:08.818+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:19:08.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 19
    except Exception as e:
    ^^^^^^
IndentationError: expected an indented block after 'try' statement on line 17
[2024-10-20T23:19:08.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:08.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.071 seconds
[2024-10-20T23:19:38.910+0000] {processor.py:186} INFO - Started process (PID=3043) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:38.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:19:38.913+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:19:38.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:38.959+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:19:38.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 19
    except Exception as e:
    ^^^^^^
IndentationError: expected an indented block after 'try' statement on line 17
[2024-10-20T23:19:38.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:19:38.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.081 seconds
[2024-10-20T23:20:09.401+0000] {processor.py:186} INFO - Started process (PID=3108) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:09.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:20:09.404+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:20:09.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:09.469+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:20:09.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 19
    except Exception as e:
    ^^^^^^
IndentationError: expected an indented block after 'try' statement on line 17
[2024-10-20T23:20:09.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:09.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.115 seconds
[2024-10-20T23:20:39.575+0000] {processor.py:186} INFO - Started process (PID=3175) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:39.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:20:39.577+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:20:39.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:39.621+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:20:39.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 19
    except Exception as e:
    ^^^^^^
IndentationError: expected an indented block after 'try' statement on line 17
[2024-10-20T23:20:39.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:20:39.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.084 seconds
[2024-10-20T23:21:10.107+0000] {processor.py:186} INFO - Started process (PID=3242) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:10.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:21:10.110+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:21:10.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:10.159+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:21:10.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 24
    except Exception as e:
IndentationError: expected an indented block after 'with' statement on line 21
[2024-10-20T23:21:10.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:10.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.081 seconds
[2024-10-20T23:21:40.583+0000] {processor.py:186} INFO - Started process (PID=3309) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:40.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:21:40.587+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:21:40.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:40.662+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:21:40.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:21:40.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:21:40.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.116 seconds
[2024-10-20T23:22:11.139+0000] {processor.py:186} INFO - Started process (PID=3376) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:11.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:22:11.143+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:22:11.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:11.206+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:22:11.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:22:11.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:11.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.127 seconds
[2024-10-20T23:22:41.761+0000] {processor.py:186} INFO - Started process (PID=3443) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:41.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:22:41.766+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:22:41.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:41.850+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:22:41.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:22:41.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:22:41.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.137 seconds
[2024-10-20T23:23:12.155+0000] {processor.py:186} INFO - Started process (PID=3510) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:12.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:23:12.159+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:23:12.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:12.232+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:23:12.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:23:12.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:12.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.119 seconds
[2024-10-20T23:23:42.891+0000] {processor.py:186} INFO - Started process (PID=3577) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:42.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:23:42.896+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:23:42.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:42.969+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:23:42.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 30
    self.
         ^
SyntaxError: invalid syntax
[2024-10-20T23:23:42.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:23:43.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.132 seconds
[2024-10-20T23:24:13.577+0000] {processor.py:186} INFO - Started process (PID=3644) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:13.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:24:13.583+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:24:13.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:13.640+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:24:13.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 30
    self.
         ^
SyntaxError: invalid syntax
[2024-10-20T23:24:13.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:13.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.109 seconds
[2024-10-20T23:24:43.805+0000] {processor.py:186} INFO - Started process (PID=3711) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:43.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:24:43.812+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:24:43.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:43.904+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:24:43.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:24:43.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:24:43.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.157 seconds
[2024-10-20T23:25:14.101+0000] {processor.py:186} INFO - Started process (PID=3778) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:14.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:25:14.108+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:25:14.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:14.169+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:25:14.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:25:14.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:14.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.118 seconds
[2024-10-20T23:25:44.335+0000] {processor.py:186} INFO - Started process (PID=3843) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:44.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:25:44.339+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:25:44.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:44.406+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:25:44.398+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:25:44.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:25:44.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.111 seconds
[2024-10-20T23:26:14.613+0000] {processor.py:186} INFO - Started process (PID=3910) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:14.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:26:14.617+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:26:14.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:14.656+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:26:14.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 33
    raise Exception(f'{schema_file} Schema Submission Failed To Submit With {response.status_code})
                    ^
SyntaxError: unterminated f-string literal (detected at line 33)
[2024-10-20T23:26:14.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:14.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.086 seconds
[2024-10-20T23:26:45.057+0000] {processor.py:186} INFO - Started process (PID=3977) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:45.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:26:45.062+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:26:45.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:45.133+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:26:45.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 8, in <module>
    from pinot_schema_operator import PinotSchemaSubmitOperator
  File "/opt/airflow/plugins/pinot_schema_operator.py", line 33
    raise Exception(f'{schema_file} Schema Submission Failed To Submit With {response.status_code})
                    ^
SyntaxError: unterminated f-string literal (detected at line 33)
[2024-10-20T23:26:45.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:26:45.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.129 seconds
[2024-10-20T23:27:15.918+0000] {processor.py:186} INFO - Started process (PID=4045) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:15.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:27:15.923+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:27:15.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:16.011+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:27:15.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:27:16.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:16.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.137 seconds
[2024-10-20T23:27:46.431+0000] {processor.py:186} INFO - Started process (PID=4111) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:46.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:27:46.435+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:27:46.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:46.487+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:27:46.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:27:46.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:27:46.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.096 seconds
[2024-10-20T23:28:17.084+0000] {processor.py:186} INFO - Started process (PID=4176) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:17.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:28:17.089+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:28:17.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:17.138+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:28:17.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:28:17.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:17.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.107 seconds
[2024-10-20T23:28:47.828+0000] {processor.py:186} INFO - Started process (PID=4243) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:47.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:28:47.832+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:28:47.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:47.890+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:28:47.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:28:47.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:28:47.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.110 seconds
[2024-10-20T23:29:18.757+0000] {processor.py:186} INFO - Started process (PID=4310) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:18.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:29:18.762+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:29:18.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:18.816+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:29:18.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:29:18.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:18.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.108 seconds
[2024-10-20T23:29:49.048+0000] {processor.py:186} INFO - Started process (PID=4377) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:49.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:29:49.052+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:29:49.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:49.114+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:29:49.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:29:49.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:29:49.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.110 seconds
[2024-10-20T23:30:19.668+0000] {processor.py:186} INFO - Started process (PID=4450) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:19.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:30:19.671+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:30:19.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:19.702+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:30:19.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:30:19.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:19.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.070 seconds
[2024-10-20T23:30:49.950+0000] {processor.py:186} INFO - Started process (PID=4516) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:49.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:30:49.955+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:30:49.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:50.011+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:30:50.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:30:50.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:30:50.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.112 seconds
[2024-10-20T23:31:20.327+0000] {processor.py:186} INFO - Started process (PID=4583) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:20.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:31:20.332+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:20.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:20.382+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:20.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:31:20.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:20.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.108 seconds
[2024-10-20T23:31:50.681+0000] {processor.py:186} INFO - Started process (PID=4650) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:50.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:31:50.688+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:50.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:50.738+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:50.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:31:50.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:31:50.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.113 seconds
[2024-10-20T23:32:21.420+0000] {processor.py:186} INFO - Started process (PID=4718) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:21.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:32:21.424+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:21.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:21.467+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:21.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:32:21.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:21.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.089 seconds
[2024-10-20T23:32:51.936+0000] {processor.py:186} INFO - Started process (PID=4786) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:51.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:32:51.942+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:51.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:51.996+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:51.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:32:51.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:32:52.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.109 seconds
[2024-10-20T23:33:22.512+0000] {processor.py:186} INFO - Started process (PID=4854) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:22.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:33:22.517+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:22.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:22.576+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:22.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:33:22.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:22.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.113 seconds
[2024-10-20T23:33:53.381+0000] {processor.py:186} INFO - Started process (PID=4922) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:53.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:33:53.387+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:53.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:53.465+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:53.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:33:53.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:33:53.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.150 seconds
[2024-10-20T23:34:24.137+0000] {processor.py:186} INFO - Started process (PID=4990) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:24.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:34:24.141+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:24.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:24.187+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:24.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:34:24.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:24.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.094 seconds
[2024-10-20T23:34:54.964+0000] {processor.py:186} INFO - Started process (PID=5057) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:54.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:34:54.968+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:54.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:55.020+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:55.011+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:34:55.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:34:55.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.098 seconds
[2024-10-20T23:35:25.846+0000] {processor.py:186} INFO - Started process (PID=5125) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:25.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:35:25.851+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:25.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:25.901+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:25.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:35:25.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:25.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.094 seconds
[2024-10-20T23:35:56.317+0000] {processor.py:186} INFO - Started process (PID=5193) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:56.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:35:56.323+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:56.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:56.384+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:56.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:35:56.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:35:56.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.118 seconds
[2024-10-20T23:36:27.339+0000] {processor.py:186} INFO - Started process (PID=5261) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:27.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:36:27.345+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:27.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:27.399+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:27.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:36:27.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:27.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.104 seconds
[2024-10-20T23:36:58.046+0000] {processor.py:186} INFO - Started process (PID=5329) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:58.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:36:58.050+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:58.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:58.092+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:58.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:36:58.094+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:36:58.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.085 seconds
[2024-10-20T23:37:28.925+0000] {processor.py:186} INFO - Started process (PID=5397) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:28.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:37:28.928+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:28.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:28.959+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:28.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:37:28.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:28.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.075 seconds
[2024-10-20T23:37:59.126+0000] {processor.py:186} INFO - Started process (PID=5465) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:59.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:37:59.130+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:59.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:59.171+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:59.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:37:59.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:37:59.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.090 seconds
[2024-10-20T23:38:29.461+0000] {processor.py:186} INFO - Started process (PID=5534) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:38:29.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:38:29.466+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:29.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:38:29.506+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:29.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:38:29.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:38:29.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.089 seconds
[2024-10-20T23:39:00.219+0000] {processor.py:186} INFO - Started process (PID=5602) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:00.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:39:00.222+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:00.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:00.259+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:00.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:39:00.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:00.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.084 seconds
[2024-10-20T23:39:30.500+0000] {processor.py:186} INFO - Started process (PID=5669) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:30.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:39:30.505+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:30.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:30.541+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:30.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:39:30.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:39:30.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.079 seconds
[2024-10-20T23:40:01.083+0000] {processor.py:186} INFO - Started process (PID=5737) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:01.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:40:01.087+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:01.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:01.147+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:01.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:40:01.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:01.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.101 seconds
[2024-10-20T23:40:31.563+0000] {processor.py:186} INFO - Started process (PID=5805) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:31.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:40:31.566+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:31.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:31.598+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:31.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:40:31.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:40:31.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.072 seconds
[2024-10-20T23:41:01.885+0000] {processor.py:186} INFO - Started process (PID=5874) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:01.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:41:01.889+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:01.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:01.947+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:01.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:41:01.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:01.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.099 seconds
[2024-10-20T23:41:32.349+0000] {processor.py:186} INFO - Started process (PID=5942) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:32.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:41:32.354+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:32.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:32.387+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:32.378+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:41:32.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:41:32.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.077 seconds
[2024-10-20T23:42:03.368+0000] {processor.py:186} INFO - Started process (PID=6010) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:03.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:42:03.371+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:03.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:03.410+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:03.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:42:03.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:03.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.080 seconds
[2024-10-20T23:42:33.550+0000] {processor.py:186} INFO - Started process (PID=6078) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:33.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:42:33.555+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:33.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:33.590+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:33.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:42:33.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:42:33.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.088 seconds
[2024-10-20T23:43:03.813+0000] {processor.py:186} INFO - Started process (PID=6146) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:03.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:43:03.820+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:03.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:03.887+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:03.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:43:03.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:03.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.130 seconds
[2024-10-20T23:43:34.079+0000] {processor.py:186} INFO - Started process (PID=6214) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:34.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:43:34.087+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:34.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:34.141+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:34.129+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:43:34.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:43:34.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.107 seconds
[2024-10-20T23:44:04.741+0000] {processor.py:186} INFO - Started process (PID=6282) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:04.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:44:04.746+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:04.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:04.793+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:04.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:44:04.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:04.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.105 seconds
[2024-10-20T23:44:35.360+0000] {processor.py:186} INFO - Started process (PID=6350) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:35.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:44:35.364+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:35.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:35.398+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:35.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:44:35.399+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:44:35.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.079 seconds
[2024-10-20T23:45:05.842+0000] {processor.py:186} INFO - Started process (PID=6418) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:05.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:45:05.845+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:05.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:05.869+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:05.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:45:05.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:05.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.061 seconds
[2024-10-20T23:45:36.382+0000] {processor.py:186} INFO - Started process (PID=6487) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:36.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:45:36.386+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:36.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:36.423+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:36.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:45:36.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:45:36.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.076 seconds
[2024-10-20T23:46:06.717+0000] {processor.py:186} INFO - Started process (PID=6555) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:06.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:46:06.723+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:06.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:06.761+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:06.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:46:06.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:06.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.082 seconds
[2024-10-20T23:46:37.084+0000] {processor.py:186} INFO - Started process (PID=6623) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:37.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:46:37.088+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:37.087+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:37.145+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:37.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:46:37.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:46:37.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.100 seconds
[2024-10-20T23:47:07.472+0000] {processor.py:186} INFO - Started process (PID=6692) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:07.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:47:07.476+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:07.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:07.506+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:07.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:47:07.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:07.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.078 seconds
[2024-10-20T23:47:38.037+0000] {processor.py:186} INFO - Started process (PID=6760) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:38.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:47:38.041+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:38.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:38.070+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:38.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:47:38.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:47:38.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.073 seconds
[2024-10-20T23:48:08.397+0000] {processor.py:186} INFO - Started process (PID=6828) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:08.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:48:08.400+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:08.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:08.451+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:08.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:48:08.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:08.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.089 seconds
[2024-10-20T23:48:38.662+0000] {processor.py:186} INFO - Started process (PID=6896) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:38.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:48:38.666+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:38.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:38.691+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:38.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:48:38.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:48:38.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.063 seconds
[2024-10-20T23:49:09.328+0000] {processor.py:186} INFO - Started process (PID=6964) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:09.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:49:09.332+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:09.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:09.371+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:09.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:49:09.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:09.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.075 seconds
[2024-10-20T23:49:39.837+0000] {processor.py:186} INFO - Started process (PID=7032) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:39.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:49:39.842+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:39.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:39.889+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:39.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:49:39.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:49:39.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.093 seconds
[2024-10-20T23:50:10.312+0000] {processor.py:186} INFO - Started process (PID=7100) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:10.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:50:10.316+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:10.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:10.371+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:10.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:50:10.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:10.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.104 seconds
[2024-10-20T23:50:40.588+0000] {processor.py:186} INFO - Started process (PID=7168) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:40.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:50:40.591+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:40.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:40.614+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:40.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:50:40.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:50:40.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.064 seconds
[2024-10-20T23:51:11.093+0000] {processor.py:186} INFO - Started process (PID=7236) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:11.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:51:11.097+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:11.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:11.133+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:11.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:51:11.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:11.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.075 seconds
[2024-10-20T23:51:41.709+0000] {processor.py:186} INFO - Started process (PID=7304) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:41.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:51:41.713+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:41.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:41.763+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:41.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:51:41.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:51:41.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.096 seconds
[2024-10-20T23:52:12.469+0000] {processor.py:186} INFO - Started process (PID=7372) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:12.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:52:12.473+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:12.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:12.537+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:12.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:52:12.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:12.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.109 seconds
[2024-10-20T23:52:42.796+0000] {processor.py:186} INFO - Started process (PID=7440) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:42.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:52:42.801+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:42.801+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:42.857+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:42.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:52:42.858+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:52:42.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.101 seconds
[2024-10-20T23:53:13.456+0000] {processor.py:186} INFO - Started process (PID=7509) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:13.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:53:13.459+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:13.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:13.483+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:13.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:53:13.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:13.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.068 seconds
[2024-10-20T23:53:43.755+0000] {processor.py:186} INFO - Started process (PID=7577) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:43.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:53:43.762+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:43.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:43.818+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:43.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:53:43.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:53:43.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.114 seconds
[2024-10-20T23:54:14.128+0000] {processor.py:186} INFO - Started process (PID=7645) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:14.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:54:14.132+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:14.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:14.185+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:14.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:54:14.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:14.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.096 seconds
[2024-10-20T23:54:44.499+0000] {processor.py:186} INFO - Started process (PID=7713) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:44.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:54:44.504+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:44.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:44.569+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:44.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:54:44.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:54:44.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.121 seconds
[2024-10-20T23:55:15.466+0000] {processor.py:186} INFO - Started process (PID=7781) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:15.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:55:15.470+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:15.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:15.514+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:15.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:55:15.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:15.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.088 seconds
[2024-10-20T23:55:46.465+0000] {processor.py:186} INFO - Started process (PID=7849) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:46.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:55:46.471+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:46.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:46.538+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:46.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:55:46.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:55:46.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.111 seconds
[2024-10-20T23:56:16.770+0000] {processor.py:186} INFO - Started process (PID=7917) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:16.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:56:16.774+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:16.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:16.820+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:16.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:56:16.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:16.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.092 seconds
[2024-10-20T23:56:47.177+0000] {processor.py:186} INFO - Started process (PID=7985) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:47.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:56:47.181+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:47.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:47.228+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:47.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:56:47.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:56:47.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.096 seconds
[2024-10-20T23:57:17.897+0000] {processor.py:186} INFO - Started process (PID=8054) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:17.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:57:17.901+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:17.900+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:17.950+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:17.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:57:17.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:17.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.094 seconds
[2024-10-20T23:57:48.531+0000] {processor.py:186} INFO - Started process (PID=8122) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:48.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:57:48.551+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:48.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:48.761+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:48.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:57:48.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:57:48.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.314 seconds
[2024-10-20T23:58:18.945+0000] {processor.py:186} INFO - Started process (PID=8190) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:18.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:58:18.950+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:18.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:19.011+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:19.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:58:19.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:19.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.108 seconds
[2024-10-20T23:58:49.278+0000] {processor.py:186} INFO - Started process (PID=8258) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:49.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:58:49.285+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:49.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:49.348+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:49.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:58:49.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:58:49.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.120 seconds
[2024-10-20T23:59:19.480+0000] {processor.py:186} INFO - Started process (PID=8326) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:19.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:59:19.483+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:19.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:19.531+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:19.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:59:19.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:19.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.090 seconds
[2024-10-20T23:59:49.904+0000] {processor.py:186} INFO - Started process (PID=8393) to work on /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:49.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/schema_dag.py for tasks to queue
[2024-10-20T23:59:49.909+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:49.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:49.953+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:49.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/schema_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schema_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'schema dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:59:49.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/schema_dag.py
[2024-10-20T23:59:49.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/schema_dag.py took 0.098 seconds
