[2024-10-20T23:31:59.175+0000] {processor.py:186} INFO - Started process (PID=4660) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:31:59.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:31:59.181+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:59.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:31:59.298+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:31:59.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:31:59.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:31:59.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.168 seconds
[2024-10-20T23:32:29.584+0000] {processor.py:186} INFO - Started process (PID=4728) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:32:29.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:32:29.591+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:29.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:32:29.653+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:32:29.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:32:29.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:32:29.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.121 seconds
[2024-10-20T23:33:00.187+0000] {processor.py:186} INFO - Started process (PID=4796) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:00.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:33:00.192+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:00.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:00.238+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:00.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:33:00.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:00.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.095 seconds
[2024-10-20T23:33:30.819+0000] {processor.py:186} INFO - Started process (PID=4864) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:30.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:33:30.823+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:30.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:30.876+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:33:30.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:33:30.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:33:30.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.101 seconds
[2024-10-20T23:34:01.521+0000] {processor.py:186} INFO - Started process (PID=4932) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:01.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:34:01.526+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:01.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:01.572+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:01.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:34:01.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:01.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.099 seconds
[2024-10-20T23:34:32.290+0000] {processor.py:186} INFO - Started process (PID=5000) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:32.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:34:32.294+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:32.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:32.343+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:34:32.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:34:32.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:34:32.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.098 seconds
[2024-10-20T23:35:03.138+0000] {processor.py:186} INFO - Started process (PID=5067) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:03.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:35:03.154+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:03.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:03.222+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:03.205+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:35:03.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:03.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.136 seconds
[2024-10-20T23:35:33.993+0000] {processor.py:186} INFO - Started process (PID=5135) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:33.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:35:33.999+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:33.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:34.046+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:35:34.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:35:34.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:35:34.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.102 seconds
[2024-10-20T23:36:04.528+0000] {processor.py:186} INFO - Started process (PID=5203) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:04.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:36:04.533+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:04.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:04.595+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:04.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:36:04.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:04.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.109 seconds
[2024-10-20T23:36:35.516+0000] {processor.py:186} INFO - Started process (PID=5271) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:35.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:36:35.520+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:35.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:35.576+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:36:35.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:36:35.577+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:36:35.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.100 seconds
[2024-10-20T23:37:06.449+0000] {processor.py:186} INFO - Started process (PID=5339) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:06.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:37:06.454+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:06.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:06.506+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:06.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:37:06.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:06.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.099 seconds
[2024-10-20T23:37:37.022+0000] {processor.py:186} INFO - Started process (PID=5407) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:37.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:37:37.026+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:37.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:37.082+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:37:37.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:37:37.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:37:37.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.107 seconds
[2024-10-20T23:38:07.389+0000] {processor.py:186} INFO - Started process (PID=5475) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:07.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:38:07.393+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:07.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:07.432+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:07.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:38:07.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:07.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.086 seconds
[2024-10-20T23:38:37.766+0000] {processor.py:186} INFO - Started process (PID=5544) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:37.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:38:37.774+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:37.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:37.833+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:38:37.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:38:37.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:38:37.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.113 seconds
[2024-10-20T23:39:08.701+0000] {processor.py:186} INFO - Started process (PID=5612) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:08.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:39:08.704+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:08.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:08.751+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:08.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:39:08.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:08.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.096 seconds
[2024-10-20T23:39:38.938+0000] {processor.py:186} INFO - Started process (PID=5679) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:38.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:39:38.942+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:38.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:38.980+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:39:38.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:39:38.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:39:39.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.082 seconds
[2024-10-20T23:40:09.149+0000] {processor.py:186} INFO - Started process (PID=5747) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:09.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:40:09.152+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:09.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:09.192+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:09.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:40:09.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:09.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.083 seconds
[2024-10-20T23:40:39.579+0000] {processor.py:186} INFO - Started process (PID=5815) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:39.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:40:39.582+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:39.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:39.605+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:40:39.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:40:39.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:40:39.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.067 seconds
[2024-10-20T23:41:09.985+0000] {processor.py:186} INFO - Started process (PID=5884) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:09.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:41:09.989+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:09.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:10.025+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:10.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:41:10.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:10.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.078 seconds
[2024-10-20T23:41:40.365+0000] {processor.py:186} INFO - Started process (PID=5952) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:40.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:41:40.369+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:40.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:40.415+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:41:40.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:41:40.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:41:40.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.089 seconds
[2024-10-20T23:42:10.587+0000] {processor.py:186} INFO - Started process (PID=6020) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:10.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:42:10.591+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:10.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:10.636+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:10.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:42:10.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:10.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.088 seconds
[2024-10-20T23:42:41.076+0000] {processor.py:186} INFO - Started process (PID=6088) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:41.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:42:41.080+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:41.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:41.126+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:42:41.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:42:41.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:42:41.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.097 seconds
[2024-10-20T23:43:11.657+0000] {processor.py:186} INFO - Started process (PID=6156) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:11.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:43:11.661+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:11.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:11.713+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:11.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:43:11.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:11.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.096 seconds
[2024-10-20T23:43:42.160+0000] {processor.py:186} INFO - Started process (PID=6224) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:42.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:43:42.165+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:42.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:42.193+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:43:42.187+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:43:42.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:43:42.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.075 seconds
[2024-10-20T23:44:12.824+0000] {processor.py:186} INFO - Started process (PID=6292) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:12.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:44:12.828+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:12.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:12.864+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:12.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:44:12.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:12.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.089 seconds
[2024-10-20T23:44:43.408+0000] {processor.py:186} INFO - Started process (PID=6360) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:43.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:44:43.412+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:43.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:43.437+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:44:43.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:44:43.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:44:43.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.065 seconds
[2024-10-20T23:45:13.915+0000] {processor.py:186} INFO - Started process (PID=6428) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:13.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:45:13.920+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:13.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:13.973+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:13.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:45:13.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:14.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.108 seconds
[2024-10-20T23:45:44.498+0000] {processor.py:186} INFO - Started process (PID=6497) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:44.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:45:44.503+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:44.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:44.565+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:45:44.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:45:44.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:45:44.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.106 seconds
[2024-10-20T23:46:14.729+0000] {processor.py:186} INFO - Started process (PID=6565) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:14.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:46:14.733+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:14.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:14.778+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:14.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:46:14.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:14.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.084 seconds
[2024-10-20T23:46:45.188+0000] {processor.py:186} INFO - Started process (PID=6633) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:45.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:46:45.192+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:45.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:45.235+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:46:45.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:46:45.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:46:45.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.082 seconds
[2024-10-20T23:47:15.511+0000] {processor.py:186} INFO - Started process (PID=6702) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:15.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:47:15.514+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:15.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:15.549+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:15.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:47:15.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:15.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.073 seconds
[2024-10-20T23:47:45.924+0000] {processor.py:186} INFO - Started process (PID=6769) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:45.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:47:45.927+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:45.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:45.960+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:47:45.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:47:45.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:47:45.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.072 seconds
[2024-10-20T23:48:16.173+0000] {processor.py:186} INFO - Started process (PID=6837) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:16.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:48:16.176+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:16.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:16.205+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:16.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:48:16.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:16.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.069 seconds
[2024-10-20T23:48:46.513+0000] {processor.py:186} INFO - Started process (PID=6905) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:46.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:48:46.516+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:46.515+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:46.547+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:48:46.538+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:48:46.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:48:46.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.073 seconds
[2024-10-20T23:49:17.034+0000] {processor.py:186} INFO - Started process (PID=6973) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:17.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:49:17.037+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:17.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:17.067+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:17.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:49:17.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:17.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.070 seconds
[2024-10-20T23:49:47.657+0000] {processor.py:186} INFO - Started process (PID=7041) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:47.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:49:47.661+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:47.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:47.721+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:49:47.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:49:47.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:49:47.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.102 seconds
[2024-10-20T23:50:18.162+0000] {processor.py:186} INFO - Started process (PID=7109) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:18.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:50:18.165+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:18.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:18.210+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:18.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:50:18.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:18.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.082 seconds
[2024-10-20T23:50:48.395+0000] {processor.py:186} INFO - Started process (PID=7177) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:48.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:50:48.398+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:48.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:48.422+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:50:48.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:50:48.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:50:48.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.061 seconds
[2024-10-20T23:51:18.942+0000] {processor.py:186} INFO - Started process (PID=7245) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:18.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:51:18.945+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:18.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:18.970+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:18.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:51:18.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:18.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.062 seconds
[2024-10-20T23:51:49.502+0000] {processor.py:186} INFO - Started process (PID=7313) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:49.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:51:49.506+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:49.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:49.545+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:51:49.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:51:49.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:51:49.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.082 seconds
[2024-10-20T23:52:20.480+0000] {processor.py:186} INFO - Started process (PID=7381) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:20.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:52:20.486+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:20.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:20.527+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:20.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:52:20.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:20.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.088 seconds
[2024-10-20T23:52:50.731+0000] {processor.py:186} INFO - Started process (PID=7449) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:50.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:52:50.735+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:50.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:50.787+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:52:50.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:52:50.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:52:50.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.101 seconds
[2024-10-20T23:53:21.304+0000] {processor.py:186} INFO - Started process (PID=7518) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:21.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:53:21.310+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:21.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:21.344+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:21.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:53:21.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:21.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.080 seconds
[2024-10-20T23:53:51.512+0000] {processor.py:186} INFO - Started process (PID=7586) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:51.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:53:51.518+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:51.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:51.573+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:53:51.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:53:51.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:53:51.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.115 seconds
[2024-10-20T23:54:22.006+0000] {processor.py:186} INFO - Started process (PID=7653) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:22.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:54:22.010+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:22.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:22.045+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:22.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:54:22.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:22.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.083 seconds
[2024-10-20T23:54:52.195+0000] {processor.py:186} INFO - Started process (PID=7721) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:52.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:54:52.199+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:52.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:52.247+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:54:52.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:54:52.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:54:52.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.087 seconds
[2024-10-20T23:55:23.088+0000] {processor.py:186} INFO - Started process (PID=7795) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:23.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:55:23.093+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:23.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:23.144+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:23.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:55:23.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:23.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.118 seconds
[2024-10-20T23:55:53.257+0000] {processor.py:186} INFO - Started process (PID=7863) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:53.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:55:53.261+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:53.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:53.298+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:55:53.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:55:53.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:55:53.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.077 seconds
[2024-10-20T23:56:23.445+0000] {processor.py:186} INFO - Started process (PID=7931) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:23.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:56:23.449+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:23.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:23.477+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:23.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:56:23.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:23.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.070 seconds
[2024-10-20T23:56:53.866+0000] {processor.py:186} INFO - Started process (PID=8000) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:53.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:56:53.870+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:53.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:53.931+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:56:53.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:56:53.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:56:53.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.111 seconds
[2024-10-20T23:57:24.549+0000] {processor.py:186} INFO - Started process (PID=8068) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:24.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:57:24.556+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:24.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:24.620+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:24.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:57:24.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:24.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.120 seconds
[2024-10-20T23:57:55.423+0000] {processor.py:186} INFO - Started process (PID=8136) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:55.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:57:55.428+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:55.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:55.474+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:57:55.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:57:55.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:57:55.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.108 seconds
[2024-10-20T23:58:25.638+0000] {processor.py:186} INFO - Started process (PID=8204) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:25.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:58:25.642+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:25.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:25.695+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:25.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:58:25.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:25.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.111 seconds
[2024-10-20T23:58:56.176+0000] {processor.py:186} INFO - Started process (PID=8272) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:56.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:58:56.184+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:56.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:56.273+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:58:56.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:58:56.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:58:56.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.160 seconds
[2024-10-20T23:59:27.105+0000] {processor.py:186} INFO - Started process (PID=8339) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:27.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:59:27.113+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:27.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:27.183+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:27.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:59:27.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:27.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.153 seconds
[2024-10-20T23:59:57.672+0000] {processor.py:186} INFO - Started process (PID=8406) to work on /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:57.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/table_dag.py for tasks to queue
[2024-10-20T23:59:57.680+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:57.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:57.740+0000] {logging_mixin.py:190} INFO - [2024-10-20T23:59:57.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/table_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/table_dag.py", line 20, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'table dag' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-10-20T23:59:57.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/table_dag.py
[2024-10-20T23:59:57.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/table_dag.py took 0.141 seconds
