[2024-10-25T07:16:09.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T07:16:09.626+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T07:16:09.753+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-25T07:16:09.755+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-25T07:16:09.861+0000] {taskinstance.py:2888} INFO - Executing <Task(KafkaProduceOperator): generate_txn_fact_data> on 2024-10-23 00:00:00+00:00
[2024-10-25T07:16:09.934+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-25T07:16:09.945+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2024-10-25T07:16:09.991+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transaction_facts_generator', 'generate_txn_fact_data', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/transaction_facts_generator.py', '--cfg-path', '/tmp/tmpq2y74r0f']
[2024-10-25T07:16:09.998+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask generate_txn_fact_data
[2024-10-25T07:16:10.435+0000] {task_command.py:467} INFO - Running <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-23T00:00:00+00:00 [running]> on host d993b9f280d5
[2024-10-25T07:16:11.222+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saisunny' AIRFLOW_CTX_DAG_ID='transaction_facts_generator' AIRFLOW_CTX_TASK_ID='generate_txn_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-25T07:16:11.235+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-25T07:16:11.237+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-25T07:16:11.239+0000] {logging_mixin.py:190} INFO - Current task name:generate_txn_fact_data state:running start_date:2024-10-25 07:16:09.633897+00:00
[2024-10-25T07:16:11.240+0000] {logging_mixin.py:190} INFO - Dag name:transaction_facts_generator and current dag run status:running
[2024-10-25T07:16:11.242+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T07:16:11.260+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]>: connecting to kafka_broker:9092 [('172.19.0.10', 9092) IPv4]
[2024-10-25T07:16:11.262+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-10-25T07:16:11.279+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]> returned error 111. Disconnecting.
[2024-10-25T07:16:11.280+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-25T07:16:11.312+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]>: connecting to kafka_broker:9092 [('172.19.0.10', 9092) IPv4]
[2024-10-25T07:16:11.318+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]> returned error 111. Disconnecting.
[2024-10-25T07:16:11.322+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.19.0.10', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-10-25T07:16:11.328+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/kafka_operator.py", line 54, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 902, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-25T07:16:11.542+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-25T07:16:11.545+0000] {logging_mixin.py:190} INFO - Task start:2024-10-25 07:16:09.633897+00:00 end:2024-10-25 07:16:11.540855+00:00 duration:1.906958
[2024-10-25T07:16:11.550+0000] {logging_mixin.py:190} INFO - Task:<Task(KafkaProduceOperator): generate_txn_fact_data> dag:<DAG: transaction_facts_generator> dagrun:<DagRun transaction_facts_generator @ 2024-10-23 00:00:00+00:00: scheduled__2024-10-23T00:00:00+00:00, state:running, queued_at: 2024-10-25 07:14:50.050829+00:00. externally triggered: False>
[2024-10-25T07:16:11.559+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2024-10-25T07:16:11.562+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, run_id=scheduled__2024-10-23T00:00:00+00:00, execution_date=20241023T000000, start_date=20241025T071609, end_date=20241025T071611
[2024-10-25T07:16:11.720+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T07:16:11.739+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 215 for task generate_txn_fact_data (NoBrokersAvailable; 193)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/kafka_operator.py", line 54, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 902, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-25T07:16:11.886+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-25T07:16:12.006+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-25T07:16:12.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
